version: "3.7"
services:
  www:
    build: .
    image: cheesecake-www:latest
    ports:
      - "3000:80"
    volumes:
      - .:/var/www/html/
    links:
      - db

  db:
    image: "mariadb:latest"
    restart: always
    ports:
      - "3306:3306"
    environment:
      # Make sure to change these if you're planning on using Docker for purposes other than local development!
      - MYSQL_DATABASE=fahrschule365
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=test
    volumes:
      # Uncomment the next line if you want to keep mysql in a data container
      # - db-data:/var/lib/mysql:rw
      # By default, use a bind-mounted host directory instead. It's harder to accidentally lose all your db data!
      - ./.docker/db:/var/lib/mysql:rw
      #- ./tests/data/test_db.sql:/test_db.sql:ro
      - ./.docker/var/db:/docker-entrypoint-initdb.d:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8000:80
    env_file:
      - ./.docker/.env

volumes:
  persistent: